export function renderProjectViteConfig(base: string, inline: boolean, outDir: string, script: string): string {
  return [
    'import path from "node:path";',
    'import { fileURLToPath } from "node:url";',
    'import { defineConfig } from "vite";',
    'import { projectBuildPlugin, projectBuildEntry } from "./.vitality/build-adapter";',
    'const root = path.dirname(fileURLToPath(import.meta.url));',
    "const options = { root, base: " + JSON.stringify(base) + ", outDir: " + JSON.stringify(outDir) + ", script: " + JSON.stringify(script) + " };",
    "export default defineConfig({",
    "  root, base: options.base, publicDir: false,",
    "  plugins: [projectBuildPlugin(options)],",
    "  build: {",
    '    outDir: "dist", emptyOutDir: true,',
    inline ? "    assetsInlineLimit: Number.POSITIVE_INFINITY," : "    // assetsInlineLimit: Vite default,",
    '    rolldownOptions: { input: projectBuildEntry, output: { entryFileNames: ".vitality-entry.js" } },',
    "  },",
    "});",
    "",
  ].join("\n");
}

export const projectReadme = [
  "# Vitality wrapper",
  "",
  "The original project inputs are preserved here. Generation ran no build and installed nothing.",
  "",
  "Run these commands manually:",
  "",
  "    bun install",
  "    bun run build",
  "    bun run serve",
  "",
  "The TypeScript Vite configuration runs the preserved package builder inside this wrapper,",
  "then packages its static output into dist/. Serve previews the completed site at the selected base.",
  "The original project's directory and build output are not used at build time.",
  "",
  "Native compiled modules, workers and URL-loaded assets retain their filenames. They are not",
  "imported assets affected by assetsInlineLimit. The original builder receives VITALITY_BASE",
  "and BASE_PATH. Literal root URLs naming output files are rebased; API and remote URLs are not.",
  "Re-run give into a new wrapper after changing the original source.",
  "",
].join("\n");

export function renderViteConfig(base: string, inlineAssets: boolean, pages: string[]): string {
  const inputEntries = ["index.html", ...pages];
  const input = Object.fromEntries(inputEntries.map((file, index) => [
    index === 0 ? "index" : `page-${index}`,
    file,
  ]));
  const singlePageOutput = pages.length === 0
    ? `,
        output: {
          codeSplitting: false,
          entryFileNames: "assets/index.js",
          assetFileNames(asset) {
            const names = asset.names ?? [];
            return names.some((name) => name.endsWith(".css"))
              ? "assets/index.css"
              : "assets/[name][extname]";
          },
        }`
    : "";
  return `import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vite";

const root = path.dirname(fileURLToPath(import.meta.url));
const input = ${JSON.stringify(input, null, 2)};

export default defineConfig({
  root,
  base: ${JSON.stringify(base)},
  publicDir: "public",
  build: {
    outDir: "dist",
    emptyOutDir: true,
    cssCodeSplit: false,
    modulePreload: false,
    ${inlineAssets ? "assetsInlineLimit: Number.POSITIVE_INFINITY," : "// assetsInlineLimit: Vite default,"}
    rolldownOptions: {
      input: Object.fromEntries(
        Object.entries(input).map(([name, file]) => [name, path.resolve(root, file)]),
      )${singlePageOutput}
    },
  },
});
`;
}

export const generatedTsconfig = `{
  "compilerOptions": {
    "target": "ES2022",
    "useDefineForClassFields": true,
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "allowJs": true,
    "checkJs": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "noCheck": true
  },
  "include": ["src", "vite.config.ts"]
}
`;

export const generatedReadme = `# Vitified project

This directory is a source wrapper generated by Vitality. It contains no
installed dependencies and no production build.

\`src/main.ts\` is the root module. Local ES modules detected through HTML and
module imports live under \`src/app/\` as TypeScript. Genuine secondary HTML
entries retain their source routes; unreachable HTML, repository documentation,
and test pages are not treated as production entries.

\`vite.config.ts\` owns the selected public base, asset-inline setting, and
ordinary Vite build topology. Vitality adds no runtime asset registry and does
not copy the source repository into \`dist/\`. URL-addressed JSON manifests
that must retain sibling-relative links use Vite's ordinary \`public/\`
directory. Classic scripts and static-host control files use that same native
path; everything else stays in the imported source graph.

Run the toolchain explicitly when ready:

\`\`\`bash
bun install
bun run serve
bun run build
\`\`\`
`;
